### ISSUE TITLE
the vc kicks users out for no reason

### ISSUE THREAD

**Issue by scottoss** [revoltchat/vortex#18]
i hear audio and it does work but it auto disconnect after like 1 minute

**Comment by jim3692** [comment]
If you run Revolt behind Nginx, you have to add these to the WebSockets proxies
```
proxy_read_timeout 86400s;
proxy_send_timeout 86400s;
```
Check my full Nginx Revolt configuration [here](https://github.com/jim3692/self-hosted/blob/master/sites-available/revolt/nginx.template.conf)

**Comment by IowaZoomer** [comment]
I'm also experiencing this issue. However, I suspect it may be caused by something different. I've tried using the nginx site configuration above along with a couple of other templates people have provided. The result is still the same though. Even when using a clean docker image. A user in the vc will drop at random and have to join back. Sometimes those who weren't kicked from the vc have to mute then unmute their mic in order for the person who joined back to hear them again.

**Comment by IowaZoomer** [comment]
> I'm also experiencing this issue. However, I suspect it may be caused by something different. I've tried using the nginx site configuration above along with a couple of other templates people have provided. The result is still the same though. Even when using a clean docker image. A user in the vc will drop at random and have to join back. Sometimes those who weren't kicked from the vc have to mute then unmute their mic in order for the person who joined back to hear them again.

I should also add that I have cloudflare standing in front of my instance. Websocket traffic is also proxied through cloudflare now along with https. I wonder if that's causing some sort of disruption leading to users in my instance getting randomly disconnected.

**Comment by jim3692** [comment]
You probably need to check Cloudflare's documentation or contact their support. In my setup, users connect directly to my nginx proxy.

**Comment by insertish** [comment]
Can't tell if this is related to revolt.chat or a self-hosted instance;

Please re-open if this is an issue relating to revolt.chat otherwise:

In an effort to clean up the global issue tracker, I'm currently consolidating all issues regarding self-hosting Vortex into https://github.com/revoltchat/vortex/issues/23#issuecomment-1113594595.
